### ISSUE TITLE
VaccinationPractitioner#identifier validation wrong?

### ISSUE THREAD

**Issue by TobiasStill** [kassenaerztliche-bundesvereinigung/MIOParser#3]
Hello, I am getting a validation-error from MioParser when I create a vaccination-practitioner with more than one identifier:

{"errors":[{"message":"Das Array enthält 2 sollte aber maximal 1 Element enthalten","resource":"urn:uuid:20597e0e-cb2a-45b3-95f0-dc3dbdb617c3","path":"Practitioner.identifier","value":"[{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"LANR\"}]},\"system\":\"https://fhir.kbv.de/NamingSystem/KBV_NS_Base_ANR\",\"value\":\"838382202\"},{\"type\":{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v2-0203\",\"code\":\"LANR\"}]},\"system\":\"https://fhir.kbv.de/NamingSystem/KBV_NS_Base_ANR\",\"value\":\"452678935\"}]"}]}

Either I am doing something wrong or the validation is faulty since the specification allows for multiple identifiers. Could you please help?

Thanks, best
Tobias

**Comment by mioviewer** [comment]
Hello Tobias,

checkout the specification here https://simplifier.net/im1x0/kbvprmiovaccinationpractitioner
Practitioner.identifier has the constraint of 1..1, therefore only one identifier is allowed.

Hope this helps!

**Comment by TobiasStill** [comment]
I have seen this but it is somehow ambivalent since identifier may have multiple entries, for example Practitioner.identifier:ANR with 0..*. Anyway it would be factually not correct since a practitioner may have multiple identifiers (e.g. LANRs) in real life and I have the requirement to model it this way. By the way this only affects the Typescript MioParser library, since the XML schema allows for multiple identifiers and they are accepted, also by the MIO viewer. 
Bottomlline: It must be possible for a practitioner to have multiple identifiers.

**Comment by mio42** [comment]
It is correct that a practitioner may have multiple identifiers and should be able to specify them. We will take this for the next version and adjust the cardinality of the identifier.
